version: '3.5'

networks:
  test:
    external: true

services:
  grafana:
    image: 'grafana/grafana:latest'
    networks:
      - test
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      CORS_ALLOW_ORIGIN: '*'
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./demo-cluster/configs/grafana/provisioning:/etc/grafana/provisioning
      - ./demo-cluster/configs/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  prometheus:
    image: 'prom/prometheus:latest'
    networks:
      - test
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ../user/configs/prometheus/test-prometheus.yml:/etc/prometheus/test-prometheus.yml
    command: '--config.file=/etc/prometheus/test-prometheus.yml'