version: '3'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 3333:3333
    command: npm run backend

  timescaledb:
    build:
      context: .
      dockerfile: Dockerfile-database
    ports:
      - 5432:5432
    networks:
      my-network:
        ipv4_address: 172.18.0.10
    # volumes:
    #   - timescaledb-data:/var/lib/postgresql/data

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
# volumes:
#   timescaledb-data:
#     external: true
