# Use the Docker socket from the extension backend:
# https://docs.docker.com/desktop/extensions-sdk/guides/use-docker-socket-from-backend/
services:
  KafkaSonar:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: kafkasonar
    ports:
      # Expose port 3333 to the host so that you can see metrics on localhost:3333
      # - 5175:5175
      - 3333:3333
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock