# Use the Docker socket from the extension backend:
# https://docs.docker.com/desktop/extensions-sdk/guides/use-docker-socket-from-backend/
services:
  kafka-sonar:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: kafka-sonar
    networks:
      - kafka-sonar
    ports:
      # Expose port 3332 to the host so that you can see metrics on localhost:3332
      # - 5175:5175
      - 3332:3332
    volumes:
    # create named volume which is mapped to the /user directory in the extension container
    # this /user directory is copied into the extension container in the Dockerfile 
      - user:/backend/user
      - /var/run/docker.sock.raw:/var/run/docker.sock

  # timescaledb:
  #   image: timescale/timescaledb:latest-pg13
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - POSTGRES_DB=kafka_sonar_db
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - timescaledb-data:/var/lib/postgresql/data
  #     - data.sql:/docker-entrypoint-initdb.d/data.sql

  timescaledb:
    image: firenaysh/kafka-sonar-tsdb:latest
    container_name: timescaledb
    networks:
      - kafka-sonar
    ports:
      - 5432:5432
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  user:
  timescaledb-data:
  # data.sql:

networks:
  kafka-sonar:
    driver: bridge
    name: kafka-sonar