services:
  kafkasonar:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: kafkasonar
    networks:
      - kafkasonar
    ports:
      - 3332:3332
    volumes:
      # create named volume which is mapped to the backend/user directory in the extension container
      # this /user directory is copied into the extension container in the Dockerfile
      - user:/backend/user
      - /var/run/docker.sock.raw:/var/run/docker.sock

  timescaledb:
    image: kafkasonar/kafkasonar-tsdb:latest
    container_name: timescaledb
    networks:
      - kafkasonar
    ports:
      - 5432:5432
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  user:
  timescaledb-data:

networks:
  kafkasonar:
    driver: bridge
    name: kafkasonar
