version: '3'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 3333:3333
    command: npm run backend
  timescaledb:
    build:
      context: .
      dockerfile: Dockerfile-database
    ports:
      - 5432:5432
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  timescaledb-data:
